title: Wizards of Lua
description: The Art of Spell Crafting
theme: jekyll-theme-midnight
encoding: "utf-8"
show_header: false
show_dir_listing: false
defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      type: modules
    values:
      layout: default
collections:
  modules:
    output: true
    permalink: /modules/:path/
